services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ICINF
      POSTGRES_PASSWORD: ICINF
      POSTGRES_DB: compra_venta
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .:/workspace
  
  # Contenedor MongoDB para la base de datos NoSQL
  mongodb:
    image: mongo:6.0
    container_name: mongodb_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ICINF
      MONGO_INITDB_ROOT_PASSWORD: ICINF
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - .:/workspace

volumes:
  postgres_data:
  mongo_data:
